trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x' # Specify the Python version you want to use
    addToPath: true

- script: |
    # Install dependencies using pip
    pip install -r requirements.txt

    # Run any build scripts or commands here
    python test.py build
  displayName: 'Build Python Project'
